server.port=8435
#spring.datasource.url=jdbc:mysql://121.43.168.132:3307/wxrrd
#spring.datasource.username=maxwell
#spring.datasource.password=ED81A84EC3B290A4EFA26122test
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://10.110.1.3:3881/wxrrd
spring.datasource.username=wxrrd_main2
spring.datasource.password=6q9IQLwqHLq0XTMknjjI
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
