  
log4j.rootLogger = debug,stdout,D,E

#���������̨   
log4j.appender.stdout=org.apache.log4j.ConsoleAppender   
#��ʽΪTTCCLayout   
log4j.appender.stdout.layout=org.apache.log4j.TTCCLayout 

log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Threshold=INFO
log4j.appender.stdout.Target=System.out
log4j.appender.stdout.Encoding=UTF-8
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss}[%t] %-3p %c %x - %m%n

  ### �������־�ļ� ###
log4j.appender.D = org.apache.log4j.DailyRollingFileAppender
log4j.appender.D.File = logs/warn.log
log4j.appender.D.Append = true
log4j.appender.D.Threshold = warn 
## ���DEBUG�������ϵ���־
log4j.appender.D.layout = org.apache.log4j.PatternLayout
log4j.appender.D.layout.ConversionPattern = %d{yyyy-MM-dd HH:mm:ss}[%t] %-3p %c %x - %m%n


### �������־�ļ� ###
log4j.appender.D = org.apache.log4j.DailyRollingFileAppender
log4j.appender.D.File = logs/info.log
log4j.appender.D.Append = true
log4j.appender.D.Threshold = INFO 
## ���DEBUG�������ϵ���־
log4j.appender.D.layout = org.apache.log4j.PatternLayout
log4j.appender.D.layout.ConversionPattern = %d{yyyy-MM-dd HH:mm:ss}[%t] %-3p %c %x - %m%n

### �����쳣��Ϣ�������ļ� ###
log4j.appender.E = org.apache.log4j.DailyRollingFileAppender
log4j.appender.E.File = logs/error.log 
## �쳣��־�ļ���
log4j.appender.E.Append = true
log4j.appender.E.Threshold = ERROR 
## ֻ���ERROR�������ϵ���־!!!
log4j.appender.E.layout = org.apache.log4j.PatternLayout
#log4j.appender.E.layout.ConversionPattern = %-d{yyyy-MM-dd HH:mm:ss}  [ %t:%r ] - [ %p ]  %m%n 
log4j.appender.E.layout.ConversionPattern = %d{yyyy-MM-dd HH:mm:ss}[%t] %-3p %c %x - %m%n

#log4j.appender.db=com.neam.commons.MyJDBCAppender
#���������ý���־��Ϣ�������ݿ⣬
#�������Ŀ��Ϊ���ݿ⣨����Ҫ����־�ڿ���̨���������Ϊlog4j.appender. stdout =org.apache.log4j.ConsoleAppender������־д���ļ�������Ϊlog4j.appender.logfile=org.apache.log4j.DailyRollingFileAppender
#���������������ط���Ҫ�У���Ҫ�ɲ��й����ϣ�,��Ȼ��Ҳ�����Լ���չorg.apache.log4j.jdbc.JDBCAppender����ֻ࣬��Ҫ���������þͿ��������������������Լ���չ��MyJDBCAppender������Ϊ#log4j.appender.db=com.neam.commons.MyJDBCAppender
#log4j.appender.database.Threshold=debug
#����ʲô����Ĵ���д�뵽���ݿ���
#log4j.appender.database.BufferSize=1
#���û����С�����ǵ���1����־��Ϣ�ǲ������ݿ��һ��
#log4j.appender.database=org.apache.log4j.jdbc.JDBCAppender
#log4j.appender.database.driver=com.mysql.jdbc.Driver
#����Ҫ����־���뵽���ݿ������
#log4j.appender.database.URL=jdbc:mysql://127.0.0.1:3306/text_analysis
#log4j.appender.database.user=root
#log4j.appender.database.password=root
#log4j.appender.database.sql=insert into logtable (class,method,createtime,loglevel,msg) values ('%C','%M','%d{yyyy-MM-dd HH:mm:ss}','%p','%m')
#log4j.appender.database.layout=org.apache.log4j.PatternLayout 